version: "3.4"

services:
  adminer:
    image: adminer
    restart: ${RESTART_MODE}
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:adminer.${MAILSERVER_DOMAIN}
      - traefik.port=8080
      - traefik.docker.network=traefik-public
    networks:
      - traefik-public
      - db-net
