version: '3.4'

networks:
  traefik-public:

services:
  traefik:
    image: traefik:1.7.9
    ports:
    - target: 80
      protocol: tcp
      published: 80
      mode: ingress
    # - target: 443
    #   protocol: tcp
    #   published: 443
    #   mode: ingress
    - target: 8080
      protocol: tcp
      published: 8080
      mode: ingress
    volumes:
      - ${VOLUMES_ROOT_PATH}/traefik/logs:/opt/traefik/logs
    networks:
      - traefik-public
    labels:
      - traefik.backend=traefik
      - traefik.enable=true
      - traefik.frontend.rule=Host:traefik.${DOMAIN}
      - traefik.port=8080
      - traefik.protocol=http
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik/traefik.toml:/traefik.toml
      # - ./config/traefik/acme.json:/acme.json
    restart: ${RESTART_MODE}
