global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: "nodeexporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["nodeexporter:9100"]

  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "traefik"
    # If the traefik has authentication
    basic_auth:
      username: admin
      password: 12345
    # If the entrypoint is HTTPS
    scheme: http
    static_configs:
      - targets:
          - traefik:8080

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"
